export type ExtensionInfo = {
  name: string;
  description: string;
  lastVersion: string;
  
  isDebugging: boolean;

  isInstalled: boolean;
  installedVersion: string | null;
  updateAvailable: boolean;

}


// GENERATED BY https://app.quicktype.io/

export type NPMResponse = {
  objects: Extension[];
  total:   number;
  time:    string;
}

export type Extension = {
  package:     Package;
  flags:       Flags;
  score:       Score;
  searchScore: number;
}

export type Flags = {
  insecure:  number;
  unstable?: boolean;
}

export type Package = {
  name:        string;
  scope:       string;
  version:     string;
  description: string;
  date:        Date;
  links:       Links;
  author?:     Author;
  publisher:   Publisher;
  maintainers: Publisher[];
}

export type Author = {
  name:     string;
  email:    Email;
  url:      string;
  username: Username;
}

export type Email = string;

export type Username = string;

export type Links = {
  npm:         string;
  homepage?:   string;
  repository?: string;
  bugs?:       string;
}

export type Publisher = {
  username: Username;
  email:    Email;
}

export type Score = {
  final:  number;
  detail: Detail;
}

export type Detail = {
  quality:     number;
  popularity:  number;
  maintenance: number;
}
